#!/usr/bin/env python3
"""
Agent Scaffold Generator CLI
Interactively prompts for agent details and generates a CrewAI-style agent setup file.
"""

import re
import sys
from pathlib import Path


def prompt_non_empty(field_name: str, hint: str = "") -> str:
    """
    Prompts the user for input and ensures the value is not empty or whitespace-only.
    Gracefully handles KeyboardInterrupt and EOFError.
    """
    prompt_str = f"Enter {field_name}"
    if hint:
        prompt_str += f" ({hint})"
    prompt_str += ": "

    while True:
        try:
            value = input(prompt_str).strip()
            if value:
                return value
            print(f"[Error] {field_name} cannot be empty. Please enter a valid value.\n")
        except (KeyboardInterrupt, EOFError):
            print("\n\n[Cancelled] Operation aborted by user.")
            sys.exit(0)


def sanitize_identifier(name: str) -> str:
    """Converts a display name into a valid Python identifier (snake_case)."""
    # Replace non-alphanumeric characters with underscores
    clean = re.sub(r"[^a-zA-Z0-9_]", "_", name.strip().lower())
    # Remove leading numbers or double underscores
    clean = re.sub(r"^[^a-zA-Z_]+", "", clean)
    clean = re.sub(r"_+", "_", clean).strip("_")
    return clean or "custom_agent"


def generate_crewai_code(name: str, role: str, goal: str, backstory: str) -> str:
    """Generates a formatted Python script defining a CrewAI agent."""
    var_name = sanitize_identifier(name)
    
    # Format strings using repr or clean triple-quotes
    # For multi-line text (backstory/goal), indent nicely
    backstory_escaped = backstory.replace('"""', r'\"\"\"')
    goal_escaped = goal.replace('"""', r'\"\"\"')

    code = f'''"""
CrewAI Agent Definition: {name}
Auto-generated by agent_scaffold.py
"""

from crewai import Agent

# Define {name}
{var_name} = Agent(
    role="""{role}""",
    goal="""{goal_escaped}""",
    backstory="""{backstory_escaped}""",
    verbose=True,
    memory=True,
)

if __name__ == "__main__":
    print(f"Agent '{name}' initialized successfully.")
    print(f"Role: {{{var_name}.role}}")
    print(f"Goal: {{{var_name}.goal}}")
'''
    return code


def main() -> None:
    print("=" * 60)
    print("        CrewAI Agent Scaffold Generator")
    print("=" * 60)
    print("Please provide the details below to scaffold your agent.\n")

    agent_name = prompt_non_empty("Agent Name", "e.g., Market Research Analyst")
    role = prompt_non_empty("Role", "e.g., Senior Market Research Specialist")
    goal = prompt_non_empty("Goal", "e.g., Identify emerging AI trends in fintech")
    backstory = prompt_non_empty(
        "Backstory",
        "e.g., You are a seasoned analyst known for uncovering market opportunities",
    )

    # Determine default output file name
    default_filename = f"{sanitize_identifier(agent_name)}_agent.py"
    print(f"\nDefault output filename: {default_filename}")
    
    while True:
        try:
            custom_name = input(f"Press Enter to accept or enter custom filename [{default_filename}]: ").strip()
            if not custom_name:
                filename = default_filename
            else:
                filename = custom_name if custom_name.endswith(".py") else f"{custom_name}.py"
            break
        except (KeyboardInterrupt, EOFError):
            print("\n\n[Cancelled] Operation aborted by user.")
            sys.exit(0)

    output_path = Path(filename)
    code_content = generate_crewai_code(agent_name, role, goal, backstory)

    try:
        output_path.write_text(code_content, encoding="utf-8")
        print("\n" + "=" * 60)
        print(f"[Success] Agent scaffold saved to: {output_path.resolve()}")
        print("=" * 60)
        print("\nPreview of generated file:\n")
        print("-" * 40)
        print(code_content.strip())
        print("-" * 40)
    except OSError as err:
        print(f"\n[Error] Failed to write file '{output_path}': {err}")
        sys.exit(1)


if __name__ == "__main__":
    main()
